### ISSUE TITLE
Some markdown tags are not supports

### ISSUE THREAD

**Issue by greybax** [iamstarkov/get-md-content#3]
- tag ~~Strike through this text~~ not supports properly in this module
- tables in markdown are not supporting f.e

| Option | Description |
| --- | --- |
| data | path to data files. |
| engine | engine to be used for processing templates. |
| ext | extension to be used for dest files. |

As variant can use [markdown-it](https://www.npmjs.com/package/markdown-it) for supporting markdown tags in content article

**Comment by iamstarkov** [comment]
sorry, [commonmark](https://github.com/jgm/commonmark.js) — chosen markdown parser doesnt support neigther striked through, nor tables.

**Comment by iamstarkov** [comment]
i’m planning to rewrite this module (and others) to [mdast](https://github.com/wooorm/mdast) as more flexible approach
